### PR TITLE
fix: don't use anonymous type as type

### PR DESCRIPTION
**Pull request by asashour**
Is there a better way to get `RootNode`?

### CODE REVIEW

**Comment by skylot** [comment]
Another way is to pass `mth` as argument and use `mth.root()` but I am not sure it is better.

**Comment by asashour** [comment]
I guess `root` this way, is for better performance, with minimal memory effect (since we have a single `TypeInferenceVisitor`.

I guess the `!type.isGeneric()` is incorrect, since we need to check the classpath, but that's another investigation (for now).

**Comment by asashour** [comment]
Should we remove assignments with 0 usages instead? It would be better I guess.

**Comment by asashour** [comment]
I guess `TestConstructorInvoke` lost its need now.

**Comment by skylot** [comment]
I agree, `TestConstructorInvoke` can be removed.
And remove unused variable also was a good decision, thanks!

**Pull request merged**
