### PR TITLE
fix: return type lost after type inference

### PR DESCRIPTION
**Pull request by soldierkam**
The problem is described via test case. I'm not sure if it does break smth else.

### CODE REVIEW

**Comment by skylot** [comment]
@soldierkam thank you for a nice test, it really helps. Type inference fix not so good, but it works and doesn't break other tests :)
Anyway, current type inference approach is bad because it doesn't have enough information to make correct desicion and right now I am working on the solution. I will collect type constraints for every variable and on type update make a strict check using such constraints, also update will be cross variable and recursive which gives more powerful type propagation and inference. I commit the current state of this work to [type-inference-wip](https://github.com/skylot/jadx/tree/type-inference-wip) branch.

**Comment by sergey-wowwow** [comment]
@skylot 
How far the new approach from being finished? Can it already be used to get sources with bigger quality?

**Comment by skylot** [comment]
@sergey-wowwow almost finished, only 2 tests fail for now, but these tests with try/catch :( 
So you can try, but errors will occur.

**Comment by sergey-wowwow** [comment]
@skylot
Do they also fail for master branch? Or only here?

**Pull request merged**
