### PR TITLE
fix variable usage & caret position after rename

### PR DESCRIPTION
**Pull request by LBJ-the-GOAT**
#1099 

fix variable usage and set the caret at the new position of the renamed node.

var_usage_present

### CODE REVIEW

**Comment by Surendrajat** [comment]
Cool. So now I can use Jadx instead of JEB mostly. Great work @LBJ-the-GOAT!
My only wishlist now is `ESC` button to back and comments feature :)

**Review by skylot — APPROVED** [review]

**Comment by LBJ-the-GOAT** [comment]
> Cool. So now I can use Jadx instead of JEB mostly. Great work @LBJ-the-GOAT!
> My only wishlist now is `ESC` button to back and comments feature :)

Yeah I use JEB a lot, it has a debugger which is very useful.

**Comment by Surendrajat** [comment]
@LBJ-the-GOAT true. Debugger is a great feature which I'd like to see in free tools(maybe Jadx) someday. [SmaliIdea](https://github.com/JesusFreke/smalidea) also looks promising but no native debugging support. For Java, I'm planning to add it in my [APKLab](https://github.com/Surendrajat/APKLab) in future but currently just an idea :)

**Comment by LBJ-the-GOAT** [comment]
> @LBJ-the-GOAT true. Debugger is a great feature which I'd like to see in free tools(maybe Jadx) someday. [Smalidea](https://github.com/JesusFreke/smalidea) also looks promising but no native debugging support. For Java, I'm planning to add it in my [APKLab](https://github.com/Surendrajat/APKLab) in future but currently just an idea :)


I looked into JWDP protocol it looks like it's not much complicated, I want to implement it into Jadx but haven't get started, am still trying to make a few more other features.


> @LBJ-the-GOAT on a quick test it gives cross-refrences(usage) in a random order. Not a bit deal but is this expected?
> 
>  find-usage.mp4

sorry, I have no ideal why this happened.

**Comment by Surendrajat** [comment]
> I want to implement it into Jadx...

That will be nice. Hope you get time for that.
> sorry, I have no ideal why this happened.

No worries. It's just the order. I'll raise an issue if someone wants to look into it later.

**Pull request merged**
