### PR TITLE
feat(gui): show smali (#197)

### LINKED ISSUE #197: Have an option to display smali code side-by-side with decompiled code
Since some decompilation might fail or be inaccurate, it would be nice to have an option to view the original smali code of a class/method.

### PR DESCRIPTION
**Pull request by asashour**
Fix #197 

@jpstotz has kindly contributed.

### CODE REVIEW

**Comment by jpstotz** [comment]
Hi Ahmed,

I just gave your smali branch a try and have to say this looks quite useful. However I noticed that when a class is decompiled also automatically the smali code is generated. In general I would recommend to generate the smali code on-demand when the smali tab is clicked the first time (should be possible via `addChangeListener` on the `areaTabbedPane`). Then the user don't have to spend time and memory for generating and storing the smali code that may be never displayed.

**Comment by asashour** [comment]
Thanks for trying it out. Yes, it should be shown on demand.

**Comment by jpstotz** [comment]
I managed to eliminate one major draw-back of your implementation: The forced decompilation of all classes to temporary files. My implementation isn't perfect, but at least doe snot require any temporary files and it decompiles only one class.

To tried to make a pull request for your smali branch, but somehow GitHub refuses to do so (does not allow to select your jadx fork as pull request target). Therefore here is the link to my [smali branch](https://github.com/jpstotz/jadx/tree/smali) and my commit:
https://github.com/jpstotz/jadx/commit/840b5f284edf07420f995c5635ec399ab1833901

**Comment by asashour** [comment]
Very nice, that is indeed the major issue, I will include your changes.

**Comment by asashour** [comment]
I was able to make PR to the fork, from the web, you can select the source fork and destination fork.

image

**Comment by jpstotz** [comment]
@asashour Your screenshot shows exactly the point where I had to stop, because Github does not allow me to select your `asashour/smali` branch as base repository on the left side. 
I get a long list of jadx forks as base repository but yours is missing in the list. When I use the integrated search and search for "asa" or "asashour" no entry is left.

**Comment by asashour** [comment]
@jpstotz thanks for pointing this out, would [this](http://srcmvn.com/blog/2013/03/14/sending-a-pull-request-on-github-even-when-the-base-repository-you-want-is-missing/) help?

**Comment by cobalt232** [comment]
How about showing the byte code for each instruction in the small tab. Maybe in a row on the left?

**Comment by asashour** [comment]
> How about showing the byte code for each instruction in the small tab. Maybe in a row on the left?

Can you elaborate more? Why the actual byte code would be important?

Also, we use Baksmali, and it would be difficult to implement that, without existing options.

**Comment by cobalt232** [comment]
It would be useful for dex modifications on byte code level, as used in my project "Blackberry Manager".

**Pull request merged**
