### PR TITLE
Increase scroll speed in settings

### PR DESCRIPTION
**Pull request by alissonlauffer**
### Description
Currently, the scroll speed in settings is very slow (At least in Linux, I couldn't test in other platforms). This PR increases its speed.

Before:

https://user-images.githubusercontent.com/29029632/102722836-9a145d00-42e2-11eb-8fb8-53b247c48726.mp4

After:

https://user-images.githubusercontent.com/29029632/102722826-8832ba00-42e2-11eb-8b0e-20024eae1393.mp4

### CODE REVIEW

**Comment by skylot** [comment]
@alissonlauffer thanks!
I hope someday we will implement categories in preferences, like  [here](https://github.com/dlemmermann/PreferencesFX#preferencesfx), discussed in https://github.com/skylot/jadx/issues/454#issuecomment-466529000 :rofl: 

Can anyone confirm that solution works on other platforms?

**Review by skylot — APPROVED** [review]

**Comment by alissonlauffer** [comment]
> I hope someday we will implement categories in preferences, like [here](https://github.com/dlemmermann/PreferencesFX#preferencesfx), discussed in [#454 (comment)](https://github.com/skylot/jadx/issues/454#issuecomment-466529000)

Yeah, I agree with the idea of a preference panel just like in IDEA. Using PreferencesFX wouldn't force us to switch GUI from swing to javafx?

**Comment by skylot** [comment]
> Using PreferencesFX wouldn't force us to switch GUI from swing to javafx?

I don't mean switching, I mean just similar appearance ))

**Comment by jpstotz** [comment]
@alissonlauffer Even if the rest of Jadx would still be using Swing we would have to ship JavaFX with Jadx as JavaFx was removed from JRE/JDK.

**Pull request merged**
