### PR TITLE
Put deobfuscated files to res/ folder

### PR DESCRIPTION
**Pull request by sergey-wowwow**
The previous PR puts deobfuscated files to `root/res/` folder instead of `/root/res/res/`

### CODE REVIEW

**Comment by skylot** [comment]
@sergey-wowwow you can't apply already merged changes.
You need to add only one new commit, for this you can rewrite this branch by rebasing that commit on master.
Or you can make a new branch with a new PR.
Also, I can just apply your commit on master ))

**Comment by sergey-wowwow** [comment]
@skylot 
> Also, I can just apply your commit on master ))

Yeah, that would be awesome :D

**Comment by skylot** [comment]
@sergey-wowwow done :smile:

**Comment by sergey-wowwow** [comment]
@skylot 
Oh looks like it doesn't work from jadx-cli. I didn't test it there because I get an error in Eclipse IDE when trying to launch it
> The project: jadx-test-app which is referenced by the classpath, does not exist.

**Comment by skylot** [comment]
@sergey-wowwow 
`jadx-test-app` module was removed long time ago (in a7247e8a888506e9f744213ac3e7014e48a1c580).
So looks like you need to delete this folder if it still exists and reimport project.

**Pull request closed without merging**
