### PR TITLE
Replace jadx-core/lib/dx-1.10.jar with recent AOSP dx.jar

### PR DESCRIPTION
**Pull request by allight**
Recently support has been added to AOSP for generating and running
version 037 dex files. In order to load these we update the dx.jar
with a recent version built from AOSP.

### CODE REVIEW

**Comment by allight** [comment]
dx.jar built from commit [c3e562a](https://android.googlesource.com/platform/libcore/+/c3e562a36af501de9f828fc2d6673d4a784ba94e)  in [platform/libcore](https://android.googlesource.com/platform/libcore).

Dex version 037 support was added in commit [42b6182](https://android.googlesource.com/platform/libcore/+/42b618267da37587f794411f07a2c316a5fde3eb).

**Comment by allight** [comment]
As an example of why this patch is needed. This is a dex file generated by running the android runtime test suite. It is from [platform/art/test/964-default-iface-init-generated](https://android.googlesource.com/platform/art/+/master/test/964-default-iface-init-generated/). It tests when ART initializes static variables in interfaces.

To run:

    $ curl https://gist.githubusercontent.com/allight/d1719150866ddc7a423838d6ae9aa3ab/raw/b4b5348f418999bc68828abcbc771eb875a299e1/964-default-iface-init-generated.jar.base64 | base64 -d > 964-default-iface-init-generated.jar
    $ jadx-gui 964-default-iface-init-generated.jar

**Comment by pandalion98** [comment]
I recommend merging this @skylot

**Comment by Makohoek** [comment]
@skylot , any reason for not merging this into your master? it seems to help out at least a couple of users

**Comment by allight** [comment]
You will probably want to build a newer one than this even. In the 16 months since I uploaded this dex version 38 has been released (https://source.android.com/devices/tech/dalvik/dex-format#dex-file-magic) and newer tools will start to output that instead in some circumstances.

**Comment by z3ntu** [comment]
Fixes the issue for me.

**Comment by allight** [comment]
NB Since this was uploaded 1.5 years ago dex has gotten 2 additional versions. 38 for 'O' and 39 for post-O. These gate some new opcodes and behaviors (most notably invoke-custom & invoke-polymorphic) 

https://android.googlesource.com/platform/art/+/master/runtime/standard_dex_file.cc#22

**Comment by skylot** [comment]
Yes, I know. I already updated dx to version 13 and will try to implement new opcodes.
Thank you for information and your contribution.

**Pull request merged**
