### PR TITLE
feat: Add button to go to Android Manifest

### PR DESCRIPTION
**Pull request by xiaojye**
Icons from: https://intellij-icons.jetbrains.design/#AllIcons-expui-fileTypes-manifest
Closes https://github.com/skylot/jadx/issues/2297

### CODE REVIEW

**Comment by jpstotz** [comment]
As Jadx can not only process Android apps but also regular Java code the name "Go to Manifest" may be misleading, as a non-Android developer would interpret it as "Go to META-INF/MANIFEST.MF". Therefore I would recommend to change it in strings to the full name "AndroidManifest.xml" respectively in code to "AndroidManifest".

**Review by MrIkso — COMMENTED** [review]
Use icon from [intellij-icons.jetbrains.design](https://intellij-icons.jetbrains.design/#AllIcons-expui-fileTypes-manifest), all icons in jadx used from here.

**Comment by xiaojye** [comment]
> As Jadx can not only process Android apps but also regular Java code the name "Go to Manifest" may be misleading, as a non-Android developer would interpret it as "Go to META-INF/MANIFEST.MF". Therefore I would recommend to change it in strings to the full name "AndroidManifest.xml" respectively in code to "AndroidManifest".

Good suggestion, optimized and modified. Please refer to the latest commit [](https://github.com/skylot/jadx/pull/2296/commits/ffaefd2c3cc6469d62ee80b144a1c23c78e87644)

**Comment by xiaojye** [comment]
> Good suggestion, optimized and modified. Please refer to the latest commit [https://github.com/skylot/jadx/pull/2296/commits/ffaefd2c3cc6469d62ee80b144a1c23c78e87644](url)

Good suggestion, optimized and modified. Please refer to the latest commit [https://github.com/skylot/jadx/pull/2296/commits/ffaefd2c3cc6469d62ee80b144a1c23c78e87644](https://github.com/skylot/jadx/pull/url)

**Comment by xiaojye** [comment]
> Use icon from [intellij-icons.jetbrains.design](https://intellij-icons.jetbrains.design/#AllIcons-expui-fileTypes-manifest), all icons in jadx used from here.

Good suggestion, optimized and modified. Please refer to the latest commit [https://github.com/skylot/jadx/pull/2296/commits/ffaefd2c3cc6469d62ee80b144a1c23c78e87644](url)

**Review by skylot — APPROVED** [review]
Thanks :+1:

**Pull request merged**
