### PR TITLE
feat(gui): hex-viewer for binary asset files

### PR DESCRIPTION
**Pull request by Mino260806**
Suggested here #198

<details>
<summary>Demo Video</summary>

https://github.com/skylot/jadx/assets/53614199/690354f6-f914-439f-ad2e-1e570331750c

</details>

### Some possible improvements
- UI to configure and save number of bytes per line as a preference (currently hardcoded to 16)
- Change line numbers (at the left) to hex offsets
- Some hex specific actions (goto offset, ...)
- Implement a proper search ui as default SearchBar is hard to adapt (bytes as supperated by two spaces or space and line break)

### CODE REVIEW

**Comment by skylot** [comment]
Wow, you implemented hex viewer from scratch! Good work! :slightly_smiling_face:

Although, I want to add more things to improvements list:
 - hard-coded background colors make text unreadable in dark themes
 - it is better to use `smali` (monospaced) font from settings, and update it in `loadSettings` method (override from AbstractCodeArea)

**Comment by Mino260806** [comment]
Wait, I didn't know we could change the theme 😅
It shouldn't take me a lot of time to fix your points, I'll hop on it

**Comment by Mino260806** [comment]
Smali font did not turn great, the characters look inconveniently stretched and also take more space
<details>
<summary>Screenshot with Smali Font</summary>

image

</details>

<details>
<summary>Screenshot with normal Font</summary>

image

</details>

Why do you think we should use a monospaced font ? The normal font displays without any issues because ascii letters take the same space in most fonts, and otherwise ascii letters are aligned vertically and space characters as well, so it shouldn't result in any offsetted displaying

**Comment by skylot** [comment]
> The normal font displays without any issues because ascii letters take the same space in most fonts

Oh, I see, so normal ("editor") font from settings is fine

**Comment by Mino260806** [comment]
Nevermind, turns out my "normal" font is actually monospaced. And after more research I found some fonts that have inequal spaces.
image

I'll just stick with smali font. Should I change the label "Smali Editor font" to "Smali / Hex Editor font" ?

**Comment by skylot** [comment]
> Should I change the label "Smali Editor font" to "Smali / Hex Editor font" ?

I think just "Monospaced font" or "Monospaced font (Smali/Hex)" will be better because selection is limit only to monospaced, so it is less confusing :slightly_smiling_face:

**Comment by Mino260806** [comment]
I think it's ready now. 
Do you have in mind anything else I should fix ?

**Review by skylot — APPROVED** [review]

**Comment by skylot** [comment]
All good. Thank you for your hard work :+1:

**Comment by Mino260806** [comment]
Shouldn't #198 be closed ?

**Pull request merged**
