### PR TITLE
Implement Android App Bundle support

### PR DESCRIPTION
**Pull request by bagipro**
:exclamation: Please review the [guidelines for contributing](https://github.com/skylot/jadx/blob/master/CONTRIBUTING.md#Pull-Request-Process)

### Description
@skylot 
Please provide instructions again on how to format code before committing :)

Currently implemented support for XML files, also have to finish resource tables

### CODE REVIEW

**Comment by skylot** [comment]
> Please provide instructions again on how to format code before committing :)

Check [code formatting guide](https://github.com/skylot/jadx/wiki/Code-Formatting). In short, you just need to run
```
gradle spotlessApply 
```
Anyway, I already applied these formatting fixes :smiley:

**Review by skylot — APPROVED** [review]

**Comment by skylot** [comment]
@bagipro  I reviewed the changes and everything is good.
And here is a small list for future improvements:
- detect proto xml by file content (starting bytes or similar)
- support other `.pb` resources:
   * `resources.pb`
   * `assets.pb`
   * `BundleConfig.pb`
   * `dependencies.pb` - can help to restore dependencies for gradle export :smile:

**Comment by bagipro** [comment]
@skylot 
May you please check the PR and merge it? I need to update my tool and then research what to do with other `.pb` files

**Review by skylot — APPROVED** [review]

**Comment by skylot** [comment]
Thanks @bagipro! PR merged.

**Pull request merged**
