### PR TITLE
Understanding and may be fixing IndexOutOfBoundsException in the debugger

### PR DESCRIPTION
**Pull request by jpstotz**
Related issues: #1981 and #1841

This MR contains changes to the debugger to simplify the code to make it easier to understand (it used a lot of generic containers like SimpleEntry).

Also a central method was created to centralize the code that is going wrong in the referenced issues, not yet sure how to finally fix this...

### CODE REVIEW

**Comment by skylot** [comment]
Looks good to me. It sure uses too many nested generics :rofl:
And exception now will provide better message.

Also, I think root cause is a weird way to calculate register's number, starts here:
https://github.com/skylot/jadx/blob/912c431511b3b71550889f03c4f421759bafff63/jadx-gui/src/main/java/jadx/gui/device/debugger/DebugController.java#L897
and next uses different methods for different Android versions: 
https://github.com/skylot/jadx/blob/4705194a1d96c54f584d013ff4fb57e530323680/jadx-gui/src/main/java/jadx/gui/device/debugger/ArtAdapter.java#L21-L54
Maybe some versions not covered or mapping was changed again :cry:

**Comment by jpstotz** [comment]
I just realized that this PR is still incomplete. 

@skylot I agree that the way to calculate register's number may be root cause. Therefore it makes sense to print the used ArtAdapter in the error message. Together with some details on the used device for debugging, may be we are able to better understand what environments are causing this problem. Unfortunately the device information available in the Jadx debugger wasn't accessible in `RegisterObserver` class, and I don't know how helpful they are in this case. 

So next time we have to ask issue creator for more device details (may be `adb shell getprop` data?).

**Comment by skylot** [comment]
@jpstotz thanks for improvement :+1:

> Unfortunately the device information available in the Jadx debugger wasn't accessible in RegisterObserver class, and I don't know how helpful they are in this case.

I think we need at least Android/SDK version and method signature which cause issue, and ask for apk sample.

> So next time we have to ask issue creator for more device details (may be adb shell getprop data?).

Not sure which props we need, because if issue is vendor specific we will not be able to reproduce it. Anyway, it is worth to try.

**Comment by skylot** [comment]
@jpstotz I commit a change to move `DeviceSettings` class from `ADBDialog`, it was stored in a static field there, so I convert it to singleton. And now it is easier to use its data. Error message (for Google emulator) will contains device info and android version:
```
Register 6 does not exist (size: 5).
 Device: emulator-5554 device product:sdk_gphone64_x86_64 model:sdk_gphone64_x86_64 device:emulator64_x86_64_arm64 transport_id:1, Android: 12, ArtAdapter: AndroidPieAndAbove
 Method: com.jujing.yphook.LoginActivity.onCreate(Landroid/os/Bundle;)V
```
Also, during testing I saw many various issues:
- `Debug error: (JDWP Error Code:35) Invalid slot. for v1`
- values for method args not shown and actual registers list contains weird entries
- occasional UI update exceptions

Maybe first two related to our issue  :rofl:

**Review by skylot — APPROVED** [review]

**Pull request merged**
