### PR TITLE
improve smali printer to show bytecode

### PR DESCRIPTION
**Pull request by LBJ-the-GOAT**
#1114 
All the instruction decoding jobs had been done by @skylot since don't know when, I just put them together to print smali code.

added 3 columns to the output, 

- first column is a file offset within the dex file
- the second is bytecode
- the third one is the code offset within the method.

and added an addtional font setting it contains fixed-width fonts, for alignment of output. 

smali_bytecode_present

### CODE REVIEW

**Review by Surendrajat — COMMENTED** [review]
Nice job @LBJ-the-GOAT. I've a few comments:
- I think `ByteCode` has a very different meaning in Java world. Here simply using `Bytes` or `OpCode Bytes` is more relevent.
- Does the last comment ie. field/method offset (eg. `method@0123`) represent absolute address in dex? Or related to something? I may be mistaken about something here :)
- How much work might it require for synchronizing smali and java methods? Like scrolling in some other method moves cursor in related java code too. I'm sure it won't work for innerclasses right now. Just a thought.

**Comment by LBJ-the-GOAT** [comment]
> Nice job @LBJ-the-GOAT. I've a few comments:
> 
> * I think `ByteCode` has a very different meaning in Java world. Here simply using `Bytes` or `OpCode Bytes` is more relevent.
> * Does the last comment ie. field/method offset (eg. `method@0123`) represent absolute address in dex? Or related to something? I may be mistaken about something here :)
> * How much work might it require for synchronizing smali and java methods? Like scrolling in some other method moves cursor in related java code too. I'm sure it won't work for innerclasses right now. Just a thought.

> Okay, I think Btys is better.
> it's an offset to the start of the code item or something, I added it because the output of dexdump has it, more importantly it looks pretty pro, haha...

> It's a good idea, It might take a while, I just simply print the result now, it needs attach line info to do it.

**Review by skylot — APPROVED** [review]

**Comment by Surendrajat** [comment]
> Okay, I think Btys is better.

Cool. This will avoid the confusion.
> more importantly it looks pretty pro, haha...

Yeah. Then it needs to go in :rofl:
> I just simply print the result now, it needs attach line info to do it.

I see. Cool. It'll be a nice feature TBH. Till now Smali pane is not so useful for me.

**Review by skylot — APPROVED** [review]

**Comment by Surendrajat** [comment]
Seems like we're going to have `Bytecodes` for now.

**Comment by skylot** [comment]
> Seems like we're going to have Bytecodes for now.

Oops! Did I merged too early? Sorry :disappointed:

**Comment by Surendrajat** [comment]
Since @LBJ-the-GOAT agreed for `Bytes`, I was thinking so. But it can be done in a follow up PR too.

**Comment by LBJ-the-GOAT** [comment]
> > Seems like we're going to have Bytecodes for now.
> 
> Oops! Did I merged too early? Sorry 😞

@Surendrajat  Haha.. I was typing and then I saw it merged, so just continued to catch up some TV shows

**Pull request merged**
