### PR TITLE
Fixes duplicates entries in XML resources

### PR DESCRIPTION
**Pull request by sergey-wowwow**
:exclamation: Please review the [guidelines for contributing](https://github.com/skylot/jadx/blob/master/CONTRIBUTING.md#Pull-Request-Process)

### Description
#994

### CODE REVIEW

**Comment by sergey-wowwow** [comment]
image

**Comment by skylot** [comment]
@sergey-wowwow, unfortunately, you can't use binary search on that list because it must be sorted before search with the same comparator, and that not true here. I'm not yet sure how to better fix this so I just replace search with plain loop. Please check that it is still working as intended.

**Comment by skylot** [comment]
I just notice that we need to add `config` variable to name comparator. Othewise it renames all entries in other configs even they are not obfuscated. Also this make entries with same id have different names in different configs.
As soon this issue become more complex here some constraint we must met:
- entry names in one config and type must be unique
- entry name for same id must be preserved across different configs 
- notice that different configs can have different entry sets

I tried to fix this PR according to these constatraints, but not sure if it cover all possible cases. Please check and review :)

**Comment by sergey-wowwow** [comment]
> @sergey-wowwow, unfortunately, you can't use binary search on that list because it must be sorted before search with the same comparator, and that not true here. I'm not yet sure how to better fix this so I just replace search with plain loop. Please check that it is still working as intended.

Late night coding issues :D

**Review by skylot — APPROVED** [review]

**Comment by skylot** [comment]
@sergey-wowwow great, thanks!
Is this PR complete? Can I merge it?
Also, which issues can be closed after merge?  All these: #994 #996 #952 right?

**Comment by sergey-wowwow** [comment]
@skylot 
Yeah, I think it's complete and ready to be merged. I closed by issues, but not sure if #952 is also done, waiting for confirmation from @alissonlauffer

**Pull request merged**
